-- H2 Database schema (auto-generated by Hibernate)
CREATE TABLE jobs (
    id                  VARCHAR(36) PRIMARY KEY,
    type                VARCHAR(50) NOT NULL,
    priority            VARCHAR(20) NOT NULL,
    status              VARCHAR(20) NOT NULL,
    worker_id           VARCHAR(100),
    payload             CLOB,
    result              CLOB,
    error_message       VARCHAR(1000),
    retry_count         INT DEFAULT 0,
    max_retries         INT DEFAULT 3,
    execution_timeout   INT DEFAULT 300,
    created_at          TIMESTAMP,
    started_at          TIMESTAMP,
    completed_at        TIMESTAMP,
    updated_at          TIMESTAMP,
    metadata            CLOB,
    parent_job_id       VARCHAR(36),
    callback_url        VARCHAR(500),
    tags                VARCHAR(500),
    queue_name          VARCHAR(50),
    processing_node     VARCHAR(100),
    version             BIGINT
);

CREATE INDEX idx_job_status ON jobs(status);
CREATE INDEX idx_job_type ON jobs(type);
CREATE INDEX idx_job_priority ON jobs(priority);
CREATE INDEX idx_job_created ON jobs(created_at);
CREATE INDEX idx_job_worker ON jobs(worker_id);
